"""add rag document chunks

Revision ID: 703eb6e18ef3
Revises: ceaee9066079
Create Date: 2026-09-05 18:51:15.066893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '703eb6e18ef3'
down_revision: Union[str, Sequence[str], None] = 'ceaee9066079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_corpus_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('corpus_revision', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('word_start', sa.Integer(), nullable=False),
    sa.Column('word_end', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('text_checksum', sa.String(length=64), nullable=False),
    sa.Column('clean_text', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=False),
    sa.Column('extraction_version', sa.String(length=32), nullable=False),
    sa.Column('cleaning_version', sa.String(length=32), nullable=False),
    sa.Column('chunking_version', sa.String(length=32), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimensions', sa.SmallInteger(), nullable=False),
    sa.Column('source_key', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.fileid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_document_chunks_chunk_id'),
    sa.UniqueConstraint('file_id', 'index_version', 'chunk_index', name='uq_document_chunks_file_version_index')
    )
    op.create_index('ix_document_chunks_file_version', 'document_chunks', ['file_id', 'index_version'], unique=False)
    op.create_index('ix_document_chunks_hydrate', 'document_chunks', ['user_id', 'chunk_id', 'index_version'], unique=False)
    op.create_index('ix_document_chunks_user_file_version', 'document_chunks', ['user_id', 'file_id', 'index_version'], unique=False)
    op.add_column('file_metadata', sa.Column('active_index_version', sa.Integer(), nullable=False))
    op.add_column('file_metadata', sa.Column('corpus_revision', sa.BigInteger(), nullable=False))
    op.add_column('file_metadata', sa.Column('extraction_version', sa.String(length=32), nullable=True))
    op.add_column('file_metadata', sa.Column('cleaning_version', sa.String(length=32), nullable=True))
    op.add_column('file_metadata', sa.Column('chunking_version', sa.String(length=32), nullable=True))
    op.add_column('file_metadata', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('file_metadata', sa.Column('embedding_dimensions', sa.SmallInteger(), nullable=True))
    op.add_column('file_metadata', sa.Column('page_count', sa.Integer(), nullable=False))
    op.add_column('file_metadata', sa.Column('extracted_word_count', sa.Integer(), nullable=False))
    op.add_column('file_metadata', sa.Column('chunk_count', sa.Integer(), nullable=False))
    op.add_column('file_metadata', sa.Column('indexed_chunk_count', sa.Integer(), nullable=False))
    op.add_column('file_metadata', sa.Column('indexing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_metadata', sa.Column('indexing_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_metadata', sa.Column('rag_error_code', sa.String(length=64), nullable=True))
    op.add_column('file_metadata', sa.Column('rag_error_message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'rag_error_message')
    op.drop_column('file_metadata', 'rag_error_code')
    op.drop_column('file_metadata', 'indexing_completed_at')
    op.drop_column('file_metadata', 'indexing_started_at')
    op.drop_column('file_metadata', 'indexed_chunk_count')
    op.drop_column('file_metadata', 'chunk_count')
    op.drop_column('file_metadata', 'extracted_word_count')
    op.drop_column('file_metadata', 'page_count')
    op.drop_column('file_metadata', 'embedding_dimensions')
    op.drop_column('file_metadata', 'embedding_model')
    op.drop_column('file_metadata', 'chunking_version')
    op.drop_column('file_metadata', 'cleaning_version')
    op.drop_column('file_metadata', 'extraction_version')
    op.drop_column('file_metadata', 'corpus_revision')
    op.drop_column('file_metadata', 'active_index_version')
    op.drop_index('ix_document_chunks_user_file_version', table_name='document_chunks')
    op.drop_index('ix_document_chunks_hydrate', table_name='document_chunks')
    op.drop_index('ix_document_chunks_file_version', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('user_corpus_state')
    # ### end Alembic commands ###
