"""phase6_jwt_and_mysql_upgrade

Revision ID: ce06d2ee9755
Revises: 39c4c834f1d6
Create Date: 2026-08-28 12:31:51.093426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce06d2ee9755'
down_revision: Union[str, Sequence[str], None] = '39c4c834f1d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete unreferenced/orphaned development/test records where userid IS NULL
    op.execute("DELETE FROM file_metadata WHERE userid IS NULL;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_metadata', 'title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('file_metadata', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('file_metadata', 'tags',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    # Drop existing SET NULL foreign key constraint before making column NOT NULL
    op.drop_constraint('file_metadata_ibfk_1', 'file_metadata', type_='foreignkey')
    op.alter_column('file_metadata', 'userid',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'file_metadata', 'users', ['userid'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=100), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'status')
    op.drop_constraint(None, 'file_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('file_metadata_ibfk_1'), 'file_metadata', 'users', ['userid'], ['id'], ondelete='SET NULL')
    op.alter_column('file_metadata', 'userid',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('file_metadata', 'tags',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('file_metadata', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('file_metadata', 'title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
