"""add_next_retry_at_to_file_metadata

Revision ID: ceaee9066079
Revises: d9f1a2b3c4e5
Create Date: 2026-09-03 14:02:11.104634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceaee9066079'
down_revision: Union[str, Sequence[str], None] = 'd9f1a2b3c4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_user_status_fileid', 'file_metadata', ['userid', 'status', 'fileid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_status_fileid', table_name='file_metadata')
    op.drop_column('file_metadata', 'next_retry_at')
    # ### end Alembic commands ###
